alias zshconfig='cursor "$DOTFILES_ROOT/.zshrc"'
alias reload='source "$DOTFILES_ROOT/.zshrc"'
alias de='cd ~/Desktop && ls'
alias co='cd ~/Developer && ls'
alias gc='gc_func'
alias gcc='gcc_func'
alias dr='dr_func'
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias deleteDSFiles="find . -name '.DS_Store' -type f -delete"
alias pgen='passwordGenerator'
alias pg='pgen'
alias pingg="echo 'Pinging Google' && ping www.google.com"
